spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/media_processing
spring.datasource.username=tyson
spring.datasource.password=hello1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

media.upload.directory=uploads/original
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB